engine/urls.py
from django.conf.urls import url
from . import views

app_name = 'engine'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^charts$', views.charts, name='charts'),

    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),

    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^(?P<song_id>[0-9]+)/favoriteSong/$', views.favoriteSong, name='favoriteSong'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    
    url(r'^videos/(?P<filter_by>[a-zA_Z]+)/$', views.videos, name='videos'),    
    url(r'^(?P<video_id>[0-9]+)/favoriteVideo/$', views.favoriteVideo, name='favoriteVideo'),
    url(r'^(?P<album_id>[0-9]+)/create_video/$', views.create_video, name='create_video'),
    url(r'^(?P<album_id>[0-9]+)/delete_video/(?P<video_id>[0-9]+)/$', views.delete_video, name='delete_video'),
]

hound/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^engine/', include('engine.urls', namespace="engine")),
    url(r'^', include('engine.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

# Create your models here.
class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

class Video(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    video_title = models.CharField(max_length=250)
    video_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.video_title

engine/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Album, Song, Video

class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']

class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ['video_title', 'video_file']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

engine/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .forms import UserForm, AlbumForm, SongForm, VideoForm
from .models import Album, Song, Video
from urllib import urlopen as make_request
import json
from django.db.models import Q

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
VIDEO_FILE_TYPES = ['mp4', 'mkv']

def index (request):
    if not request.user.is_authenticated():
        return render(request, 'engine/login.html')
    else:
        albums = Album.objects.filter(user=request.user)
        song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            albums = albums.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()
            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()
            return render(request, 'engine/index.html', {
                'albums': albums,
                'songs': song_results,
            })
        else:
            albums = Album.objects.filter(user=request.user)
            return render(request, 'engine/index.html', {'albums': albums})


def charts (request):
    req = make_request("http://ws.audioscrobbler.com/2.0/?method=geo.gettopartists&country=india&limit=6&api_key=adf7412dad14f4430871365b20158495&format=json")
    india_charts = json.loads(req.read())
    artist_list = []
    for artist in india_charts['topartists']['artist']:
         artist_list.append({
         "name": artist['name'],
         "image": artist['image'][3]['#text'],
         "listeners": artist['listeners'],
         "url": artist['url']  
         })
         
    req = make_request("http://ws.audioscrobbler.com/2.0/?method=geo.gettoptracks&country=india&api_key=adf7412dad14f4430871365b20158495&format=json")
    india_charts = json.loads(req.read())
    artist_list = []
    for artist in india_charts['topartists']['artist']:
         artist_list.append({
         "name": artist['name'],
         "image": artist['image'][3]['#text'],
         "listeners": artist['listeners'],
         "url": artist['url']  
         })
    # print artist_list
    return render(request, 'engine/charts.html', {'india_charts': artist_list})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'engine/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'engine/index.html')
            else:
                return render(request, 'engine/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'engine/login.html', {'error_message': 'Invalid login'})
    return render(request, 'engine/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'engine/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'engine/register.html', context)

def create_album(request):
    if not request.user.is_authenticated():
        return render(request, 'engine/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'engine/create_album.html', context)
            album.save()
            return render(request, 'engine/detail.html', {'album': album})
        context = {
            "form": form,
        }
        return render(request, 'engine/create_album.html', context)
        
def detail(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'engine/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
        return render(request, 'engine/detail.html', {'album': album, 'user': user})

def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id)
    album.delete()
    albums = Album.objects.filter(user=request.user)
    return render(request, 'engine/index.html', {'albums': albums})
    
def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'engine/create_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'engine/create_song.html', context)

        song.save()
        return render(request, 'engine/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'engine/create_song.html', context)

def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'engine/detail.html', {'album': album})
    
def favoriteSong(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})
        
def songs(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'engine/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'engine/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })

def create_video(request, album_id):
    form = VideoForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_videos = album.video_set.all()
        for v in albums_videos:
            if v.video_title == form.cleaned_data.get("video_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that video',
                }
                return render(request, 'engine/create_video.html', context)
        video = form.save(commit=False)
        video.album = album
        video.video_file = request.FILES['video_file']
        file_type = video.video_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in VIDEO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Video file must be MP4',
            }
            return render(request, 'engine/create_video.html', context)

        video.save()
        return render(request, 'engine/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'engine/create_video.html', context)

def delete_video(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)

engine/templates/engine/detail.html
{% extends 'engine/navbar.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">
    <div class="row">
      <div class="col-sm-4 col-md-3">
          <div class="panel panel-default">
              <div class="panel-body">
                  <a href="{% url 'engine:detail' album.id %}">
                      {% if album.album_logo %}
                          <img src="{{ album.album_logo.url }}" class="img-responsive">
                      {% else %}
                          <h3>No image to display</h3>
                      {% endif %}
                  </a>
                  <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                  <h2>{{ album.artist }}</h2>
              </div>
          </div>
      </div>        


      <div class="col-sm-8 col-md-9">
        <ul class="nav nav-pills" style="margin-bottom: 10px;">
          <li role="presentation" class="active"><a href="{% url 'engine:detail' album.id %}">View All</a></li>
          <li role="presentation"><a href="{% url 'engine:create_song' album.id %}">Add New Song</a></li>
          <li role="presentation"><a href="{% url 'engine:create_video' album.id %}">Add New Video</a></li>        
        </ul>

        <div class="panel panel-default">
          <div class="panel-body">

            <h3>All Songs</h3>
            <table class="table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Audio File</th>
                  <th>Favorite</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for song in album.song_set.all %}
                  <tr>
                    <td>{{ song.song_title }}</td>
                    
                    <td>
                      <a href="{{ song.audio_file.url }}" onclick="playAudio(event, this, '{{ song.song_title }}')" target="_blank">
                        <button type="button" class="btn btn-success btn-xs" id= "{{ song.song_title }}">
                          <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                        </button>
                      </a>
                    </td>
                    
                    <td>
                      <a href="{% url 'engine:favoriteSong' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                    </td>
                    <td>
                      <form action="{% url 'engine:delete_song' album.id song.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                        <button type="submit" class="btn btn-danger btn-xs">
                          <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                        </button>
                      </form>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
    
          <div class="panel panel-default">
            <div class="panel-body">

              <h3>All Videos</h3>
              <table class="table">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Video File</th>
                    <th>Favorite</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for video in album.video_set.all %}
                    <tr>
                      <td>{{ video.video_title }}</td>
                      <td>
                        <a target="_blank" href="{{ video.video_file.url }}">
                          <button type="button" class="btn btn-success btn-xs">
                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                          </button>
                        </a>
                      </td>
                      <td>
                        <a href="{% url 'engine:favoriteVideo' video.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if video.is_favorite %}active{% endif %}"></span></a>
                      </td>
                      <td>
                        <form action="{% url 'engine:delete_video' album.id video.id %}" method="post" style="display: inline;">
                          {% csrf_token %}
                            <input type="hidden" name="song_id" value="{{ video.id }}" />
                            <button type="submit" class="btn btn-danger btn-xs">
                              <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                            </button>
                        </form>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
    
      
    </div>
</div>

{% endblock %}

engine/templates/engine/index.html
{% extends 'engine/navbar.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h3 style = "color : white">{{ user.username }}'s Albums</h3><br>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'engine:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <a href="{% url 'engine:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <form action="{% url 'engine:delete_album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <a href="{% url 'engine:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}              
          {% else %}
              <div class="col-sm-12">
                  <br>
                  <a href="{% url 'engine:create_album' %}">
                      <button type="button" class="btn btn-success">
                          <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                      </button>
                  </a>
              </div>
          {% endif %}
      </div>

</div>

{% endblock %}

engine/templates/engine/navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <title>{% block title %}MediaHound{% endblock %}</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
      <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'engine/style.css' %}"/>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
      <script src="{% static 'engine/js/script.js' %}"></script>
      <script>
        
        // var audio = document.createElement("audio");
        // var src = document.createElement("source");
        // 
        // function playAudio(e, link, btnID) {
        //   console.log(btnID);
        //   var elem = document.getElementById(btnID);
        //   var replacement = elem.innerHTML;
        // 
        //   if(replacement.indexOf("Play") !== -1) {
        //     src.src = link.href;
        //     console.log(src.src);
        //     audio.appendChild(src);
        // 
        //     console.log("Playing");
        //     replacement = replacement.split("play").join("pause").split("Play").join("Pause");
        //     audio.play();
        //     e.preventDefault();
        // 
        //   }
        //   else {
        //     console.log("Pausing");
        //     replacement = replacement.split("pause").join("play").split("Pause").join("Play");       
        //     audio.pause();
        //     e.preventDefault();
        //   }
        //   elem.innerHTML = replacement;
        // }
      </script>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'engine:index' %}">MediaHound</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'engine:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                    <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'engine:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
                    <li class="{% block videos_active %}{% endblock %}"><a href="{% url 'engine:videos' 'all' %}"><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp; Videos</a></li>
                    <li class="{% block charts_active %}{% endblock %}"><a href="{% url 'engine:charts' %}"><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>&nbsp; Charts</a></li>                
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'engine:index' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>


                      
                <ul class="nav navbar-nav navbar-right">
                    <li>

                        <a href="{% url 'engine:create_album' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'engine:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
                      
            </div>

        </div>
    </nav>
  {% block body %}
  {% endblock %}
  </body>
</html>

engine/templates/engine/songs.html
{% extends 'engine/navbar.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'engine:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'engine:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'engine:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'engine:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'engine:favoriteSong' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

engine/templates/engine/videos.html
{% extends 'engine/navbar.html' %}
{% block title %}All Songs{% endblock %}
{% block videos_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'engine:videos' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'engine:videos' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Video Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for video in video_list %}
                                <tr>
                                    <td>{{ video.video_title }}</td>
                                    <td>{{ video.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ video.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'engine:detail' video.album.id %}">
                                            <img src="{{ video.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'engine:detail' video.album.id %}">{{ video.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'engine:favoriteVideo' video.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if video.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}